#!/bin/bash
#SBATCH --job-name=A
#SBATCH --account=nwg_hauck.maresys
#SBATCH -p mpp
#SBATCH --ntasks=864 
#SBATCH --time=04:30:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH --qos=12h
#SBATCH --hint=nomultithread

set -x

module purge 
source ../env/albedo/shell

ulimit -s unlimited
export OMP_NUM_THREADS=1

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

#ln -s ../../bin/fesom.x .           # cp -n ../bin/fesom.x
#cp -n ../../config/namelist.config  .
#cp -n ../../config/namelist.forcing .
#cp -n ../../config/namelist.oce     .
#cp -n ../../config/namelist.ice     .
#cp -n ../../config/namelist.io      .
#cp -n ../../config/namelist.icepack .

date
srun --mpi=pmi2 ./fesom.x > "fesom2.0.out"
date

#qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_ollie
#fi

Resultpath='/albedo/work/projects/p_gcbocean/GCB2024/A/'
test -e $Resultpath/fesom.1980.oce.restart.nc && exit

IsInFile=$( tail -1 fesom2.0.out | grep -c should)
if (( IsInFile > 0 )); then
# submit next #job                                                                                                                             
                                                               
 echo "submitting next job"
 cp fesom2.0.out fesom.out.done 
 sbatch job_albedo
else
 echo "something is wrong, last line of fesom.out reads"
 echo $( tail -1 fesom2.0.out)
 echo "abnormal termination of job script"
fi

